<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerByg44jT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerByg44jT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerByg44jT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerByg44jT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerByg44jT\App_KernelDevDebugContainer([
    'container.build_hash' => 'Byg44jT',
    'container.build_id' => '01ae916e',
    'container.build_time' => 1576773823,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerByg44jT');
